### ISSUE TITLE
Does not build on Ubuntu 20.04

### ISSUE THREAD

**Issue by jpnielsen** [Ableton/push2-display-with-juce#5]
On Ubuntu 20.04 i did:

```
sudo apt install git build-essential pkg-config g++ libfreetype6-dev libx11-dev libxinerama-dev  libxrandr-dev libxcursor-dev mesa-common-dev libasound2-dev freeglut3-dev libxcomposite-dev libcurl4-gnutls-dev  libusb-1.0-0-dev
mkdir src
cd src
git clone --recurse-submodules https://github.com/Ableton/push2-display-with-juce.git
cd ~/src/push2-display-with-juce/Builds/LinuxMakefile
make
```

and got the error:

```
                  from ../../Source/push2/JuceToPush2DisplayBridge.cpp:21:
 ../../modules/JUCE/modules/juce_graphics/colour/juce_PixelFormats.h: In member function ‘juce::uint8& juce::PixelARGB::getAlpha()’:
 ../../modules/JUCE/modules/juce_graphics/colour/juce_PixelFormats.h:113:77: error: cannot bind packed field ‘((juce::PixelARGB*)this)->juce::PixelARGB::<anonymous>.juce::PixelARGB::<unnamed union>::comps[3]’ to ‘juce::uint8&’ {aka ‘unsigned char&’}
   113 |     forcedinline uint8& getAlpha() noexcept           { return comps [indexA]; }
       |                                                                ~~~~~~~~~~~~~^
 ../../modules/JUCE/modules/juce_graphics/colour/juce_PixelFormats.h: In member function ‘juce::uint8& juce::PixelARGB::getRed()’:
 ../../modules/JUCE/modules/juce_graphics/colour/juce_PixelFormats.h:114:77: error: cannot bind packed field ‘((juce::PixelARGB*)this)->juce::PixelARGB::<anonymous>.juce::PixelARGB::<unnamed union>::comps[2]’ to ‘juce::uint8&’ {aka ‘unsigned char&’}
   114 |     forcedinline uint8& getRed() noexcept             { return comps [indexR]; }
       |                                                                ~~~~~~~~~~~~~^
 ../../modules/JUCE/modules/juce_graphics/colour/juce_PixelFormats.h: In member function ‘juce::uint8& juce::PixelARGB::getGreen()’:
 ../../modules/JUCE/modules/juce_graphics/colour/juce_PixelFormats.h:115:77: error: cannot bind packed field ‘((juce::PixelARGB*)this)->juce::PixelARGB::<anonymous>.juce::PixelARGB::<unnamed union>::comps[1]’ to ‘juce::uint8&’ {aka ‘unsigned char&’}
   115 |     forcedinline uint8& getGreen() noexcept           { return comps [indexG]; }
       |                                                                ~~~~~~~~~~~~~^
 ../../modules/JUCE/modules/juce_graphics/colour/juce_PixelFormats.h: In member function ‘juce::uint8& juce::PixelARGB::getBlue()’:
 ../../modules/JUCE/modules/juce_graphics/colour/juce_PixelFormats.h:116:77: error: cannot bind packed field ‘((juce::PixelARGB*)this)->juce::PixelARGB::<anonymous>.juce::PixelARGB::<unnamed union>::comps[0]’ to ‘juce::uint8&’ {aka ‘unsigned char&’}
   116 |     forcedinline uint8& getBlue() noexcept            { return comps [indexB]; }
       |                                                                ~~~~~~~~~~~~~^
 
```

**Comment by jpnielsen** [comment]
```
cd ~/src/push2-display-with-juce/modules
rm -rf JUCE
git clone -b develop --recurse-submodules https://github.com/juce-framework/JUCE.git

cd ~/src/push2-display-with-juce/Builds/LinuxMakefile
make

... removed output text...

Compiling Push2Demo.cpp
../../Source/Push2Demo.cpp: In member function ‘NBase::Result Demo::openMidiDevice()’:
../../Source/Push2Demo.cpp:100:20: error: cannot convert ‘std::unique_ptr<juce::MidiInput>’ to ‘std::unique_ptr<juce::MidiInput>::pointer’ {aka ‘juce::MidiInput*’}
  100 |   midiInput_.reset(input);
      |                    ^~~~~
      |                    |
      |                    std::unique_ptr<juce::MidiInput>

```
